# Generated by Django 4.1.7 on 2023-03-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="while_blocked",
            field=models.DateField(null=True),
        ),
    ]
