# Generated by Django 4.1.6 on 2023-03-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("pages", models.PositiveSmallIntegerField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Drama", "Drama"),
                            ("Romance", "Romance"),
                            ("Ficção", "Fiction"),
                            ("Não Ficção", "Non Fiction"),
                            ("Infantil", "Kids"),
                            ("Terror", "Terror"),
                            ("Suspense", "Suspense"),
                            ("Ação e aventura", "Action Adventure"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("published_at", models.PositiveSmallIntegerField()),
                ("author", models.CharField(max_length=100)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
