# Generated by Django 4.1.7 on 2023-03-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="is_available",
            field=models.CharField(
                choices=[("Disponível", "Default"), ("Indisponível", "Indisponivel")],
                default="Disponível",
                max_length=20,
            ),
        ),
    ]
