# Generated by Django 4.1.7 on 2023-03-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="is_available",
            field=models.CharField(
                choices=[("disponível", "Default"), ("indisponível", "Indisponivel")],
                default="disponível",
                max_length=20,
            ),
        ),
    ]
