# Generated by Django 4.1.7 on 2023-03-15 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="estimated_return",
            field=models.DateField(default=datetime.date(2023, 3, 30)),
        ),
    ]
