# Generated by Django 4.1.7 on 2023-03-16 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="copy",
            name="copies_users",
        ),
    ]
