# Generated by Django 4.1.7 on 2023-03-14 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("copies", "0002_copy_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="copies_users",
            field=models.ManyToManyField(
                related_name="copies_users",
                through="loans.Loan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
