# Generated by Django 4.1.6 on 2023-03-05 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("copies", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="copy",
            name="copy_users",
        ),
        migrations.AddField(
            model_name="copy",
            name="copies_users",
            field=models.ManyToManyField(
                related_name="copies_users",
                through="copies.Loan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
